#!/usr/bin/env python3
"""Generate binary test fixtures for TFTP server integration tests.

Run: python tests/generate_fixtures.py

Creates deterministic binary files in tests/fixtures/ for reproducible tests.
Text fixtures (*.txt, *.cfg) are tracked in git; binary fixtures (*.bin) are
generated by this script and listed in .gitignore.
"""

import os
import struct

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")


def main():
    os.makedirs(FIXTURES_DIR, exist_ok=True)

    # zero.bin — 0 bytes (zero-byte edge case)
    write_file("zero.bin", b"")

    # oneblock.bin — exactly 512 bytes (one full TFTP block)
    write_file("oneblock.bin", bytes(i % 256 for i in range(512)))

    # medium.bin — 10 KB binary
    write_file("medium.bin", bytes((i * 7 + 13) % 256 for i in range(10240)))

    # large.bin — 1 MB binary (for throughput tests)
    write_file("large.bin", bytes((i * 31 + 17) % 256 for i in range(1048576)))

    print(f"Generated fixtures in {FIXTURES_DIR}:")
    for name in sorted(os.listdir(FIXTURES_DIR)):
        path = os.path.join(FIXTURES_DIR, name)
        size = os.path.getsize(path)
        print(f"  {name:20s}  {size:>10,} bytes")


def write_file(name, data):
    path = os.path.join(FIXTURES_DIR, name)
    with open(path, "wb") as f:
        f.write(data)


if __name__ == "__main__":
    main()
